Крестики Нолики
GameShowLDA/CSharpEducation pull request #1
Opened 2023-07-07 16:18 UTC by daniilsa

1.  Состоит из главного класса, который вызывает класс структуры игры
2.  Проверка комбинаций
3.  Расцветка хода
4.  Проверка корректности данных

2023-07-08 13:36 UTC, Dezodemius reviewed
Тебе нужно добавить в корневую папку репозиторий файл `.gitgnore`. В нём нужно прописать:
```
*.suo
*.user
.vs/
[Bb]in/
[Oo]bj/
``` 

В идеале, конечно, найти в интернете .gitignore для VisualStudio и просто скопировать его содержимое.
Потом закоммить это всё отдельным коммитом

2023-07-08 13:41 UTC, Dezodemius commented
После того, как справишься с .gitignore, нужно будет удалить все те добавленные папки и файлы из твоего репозитория. Сделай как здесь написано https://ru.stackoverflow.com/questions/535255/%D0%A3%D0%B4%D0%B0%D0%BB%D0%B8%D1%82%D1%8C-%D1%84%D0%B0%D0%B9%D0%BB-%D0%B8%D0%B7-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D1%8F

2023-07-17 10:39 UTC, Dezodemius requested changes

2023-07-17 10:39 UTC, Dezodemius commented on TicTacToe/Program.cs
> +    class Program
Здесь и в других классах нужно оформить по соглашению

2023-07-17 10:39 UTC, Dezodemius commented on TicTacToe/App.config
Может, удалить его? Раз изменений нет. Да и не нужен он

2023-07-17 10:39 UTC, Dezodemius commented on TicTacToe/Game.cs
> +        #region [ ПЕРЕМЕННЫЕ ]
Регионы немного не так пишутся. В соглашении есть как надо оформить. Если коротко, то нужно писать просто 
`#region Поля и свойства`. В других местах аналогично

2023-07-17 10:39 UTC, Dezodemius commented on TicTacToe/Game.cs
> +        // Игровое поле
Документация не так оформляется. Нужно через xml-доку

2023-07-17 10:39 UTC, Dezodemius commented on TicTacToe/Game.cs
> +        private void ChoosingAMove()
Артикли не нужно в названиях писать

2023-07-17 10:39 UTC, Dezodemius commented on TicTacToe/Game.cs
> +        /// Выбор хода
В конце доки нужно ещё и точку ставить

2023-07-17 10:39 UTC, Dezodemius commented on TicTacToe/Game.cs
> +                    int y = (str[2] - '0') - 1;
Вот такое обращение через индексы, тем более которые не по порядку, очень хрупкое. Я бы предложил несколько вариков:
1. Сделать одномерный массив и запрашивать одно число от 1 до 9
2. Не дать пользователю вводить пробел, а просто два числа рядом
3. Считывать каждое число по очереди и обособленно проверять их

2023-07-17 10:39 UTC, Dezodemius commented on TicTacToe/Game.cs
> +                        if (boolActiveMove) charArrMoves[x, y] = 'X';
'X' в константу или enum нужно вывести

2023-07-17 10:39 UTC, Dezodemius commented on TicTacToe/Game.cs
> +                if (CheckFinishGame() == 'X') { Console.ForegroundColor = ConsoleColor.Green; Console.WriteLine("Победа крестиков!"); boolFinishGame = true; }
Зачем же в одну строку? :/

2023-07-17 10:39 UTC, Dezodemius commented on TicTacToe/Game.cs
> +                if (CheckFinishGame() == 'X') { Console.ForegroundColor = ConsoleColor.Green; Console.WriteLine("Победа крестиков!"); boolFinishGame = true; }
Ниже аналогично нужно сделать - не в одну строку

2023-07-17 10:39 UTC, Dezodemius commented on TicTacToe/Game.cs
> +        private void RetutnGame()
Дока имени не соответствует

2023-07-17 10:39 UTC, Dezodemius commented on Task1/App.config
А точно задания по практике нужно удалять? Если слить эту ветку так, то у  тебя удалится всё в мастере

2023-07-22 08:41 UTC, Dezodemius requested changes

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
> +        /// <summary>
Объявление региона/закрытие региона должно отделяться пустой строкой от членов класса

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
>      class Game
Модификатор доступа нужон

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
>      /// </summary>
В конце доки должна быть точка

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
> +        private const char crossMove = 'X';
Константы называются с большой буквы

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
> +        private bool boolActiveMove = true;
Какое-то странное решение для смены хода

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
> +        private string[] stringArrPlayingField = new string[9];
А зачем два массива? Почему нельзя всё в одном делать?

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
> +                    arrMoves[i, j] = ' ';
Не нужно писать сокращения в названии переменных

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
> +        private void ChoosingMove()
`ChooseMove`

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
>              while (!boolFinishGame)
Не стоит писать тип переменной в её названии. Нужно давать такие названия, чтобы было понятно, что оно bool

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
> +                    int x = Convert.ToInt32(Console.ReadLine()) - 1;
А если неудачная конвертация будет? Всё упадёт

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
> +                if (CheckFinishGame() == crossMove)
Можно ведь один раз выполнить CheckFinishGame, а потом сравнивать

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
> +            if (arrMoves[0, 0] != ' ' && arrMoves[0, 0] == arrMoves[0, 1] && arrMoves[0, 0] == arrMoves[0, 2])
Будто бы, в конце строки очень много пробелов. Их нужно убрать

2023-07-22 08:41 UTC, Dezodemius commented on TicTacToe/Game.cs
> +            if (arrMoves[0, 0] != ' ' && arrMoves[0, 0] == arrMoves[0, 1] && arrMoves[0, 0] == arrMoves[0, 2])
В других местах тоже есть

2023-07-22 09:29 UTC, Dezodemius requested changes
Нужно поправить

2023-07-26 12:06 UTC, daniilsa commented on TicTacToe/Game.cs
>              while (!boolFinishGame)
Это привычка с работы)

2023-07-26 12:19 UTC, daniilsa commented on TicTacToe/Game.cs
> +                    int x = Convert.ToInt32(Console.ReadLine()) - 1;
Всё нормально будет, там конструкция try catch

2023-09-10 10:42 UTC, merged